
server:
  port: ${PORT:0}
  servlet:
    context-path: '/users'

spring:
  application:
    name: user-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car-user-db
    username: root
    password: 7777

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

swagger:
  host: localhost:${server.port}
  relativePath: /
  contextPath: ${spring.application.name}
