server:
  port: 9991

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-container:8176/eureka}
     # defaultZone: ${EUREKA_SERVER:http://localhost:8176/eureka}

spring:
  application:
    name: user-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/car-user-db?allowPublickeyRetrieval=true&SSL=false
    username: root
    password: 7777

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

swagger:
  host: localhost:9991
  relativePath: /
